ALTER SESSION SET CONTAINER=ETX;

CREATE USER ETXWEB IDENTIFIED BY ETXWDEV1;
GRANT ALL PRIVILEGES TO ETXWEB;
ALTER USER ETXWEB QUOTA UNLIMITED ON USERS;

CREATE USER ETXWEB4 IDENTIFIED BY ETXWDEV1;
GRANT ALL PRIVILEGES TO ETXWEB4;
ALTER USER ETXWEB4 QUOTA UNLIMITED ON USERS;

CREATE USER ETRUSTEX IDENTIFIED BY ETXWDEV1;
GRANT ALL PRIVILEGES TO ETRUSTEX;
ALTER USER ETRUSTEX QUOTA UNLIMITED ON USERS;

alter profile DEFAULT limit password_life_time unlimited;
alter profile DEFAULT limit PASSWORD_REUSE_TIME unlimited;
