export enum AdminRouteNames {
  ADMIN = 'admin',
  SYSTEM = 'system',
  SYS_ADMINS = 'sys_admins',
  SYS_OFFICIALS_IN_CHARGE = 'sys_officials_in_charge',
  SYS_ENTITIES = 'sys_entities',
  SYS_USERS = 'sys_users',
  SYS_CERTIFICATES = 'sys_certificates',
  SYS_LOGS = 'sys_logs',
  ROOT_CONFIGURATIONS = 'configurations',

  BUSINESS = 'business',
  BUSINESSES = 'businesses',
  BUSINESSES_OVERVIEW = 'businessesOverview',
  BUSINESS_OVERVIEW = 'businessOverview',
  BUSINESS_ADMINISTRATORS = 'businessAdministrators',
  BUSINESS_CONFIGURATIONS = 'businessConfigurations',
  BUSINESS_TEMPLATES = 'businessTemplates',
  BUSINESS_ENTITIES_OVERVIEW = 'businessEntitiesOverview',
  BUSINESS_CHANNELS = 'businessChannels',
  BUSINESS_CHANNELS_OVERVIEW = 'businessChannelsOverview',
  BUSINESS_CHANNEL = 'businessChannel',
  BUSINESS_USERS = 'businessUsers',
  BUSINESS_USER_REGISTRATION_REQUESTS = 'businessUserRegistrationRequests',
  BUSINESS_QUICK_START = 'businessQuickStart',
  BUSINESS_MESSAGE_SUMMARY_LIST_ITEMS = 'businessMessageSummaryListItems',

  ENTITIES = 'entities',
  ENTITY = 'businessEntity',
  CONFIGURATIONS = 'businessEntityConfigurations',
  ENTITY_USERS = 'businessEntityUsers',
  REGISTRATION_REQUESTS = 'businessEntityRegistrationRequests',
  MESSAGES_MONITORING = 'entityMessagesMonitoring'
}
